In [1]:
from scipy.stats import norm


In [2]:
norm.pdf(0)

0.3989422804014327

In [3]:
norm.pdf(0, loc = 5, scale = 10)

0.035206532676429952

In [5]:
# Scale refers to standard deviation

In [6]:
import numpy as np
r = np.random.random(10)

In [7]:
norm.pdf(r)

array([ 0.38013086,  0.39894116,  0.37813718,  0.39890895,  0.26466628,
        0.34173944,  0.36272967,  0.38112916,  0.30243101,  0.33890241])

In [8]:
norm.logpdf(r)

array([-0.96723973, -0.91894135, -0.97249825, -0.91902209, -1.32928555,
       -1.0737067 , -1.01409742, -0.96461695, -1.19590209, -1.0820431 ])

In [9]:
norm.cdp(r)

AttributeError: 'norm_gen' object has no attribute 'cdp'

In [10]:
norm.cdf(r)

array([ 0.62202718,  0.50094748,  0.62827612,  0.50515716,  0.81751134,
        0.71101758,  0.66867387,  0.61877037,  0.77164125,  0.71605007])

In [11]:
norm.logcdf(r)

array([-0.47477149, -0.69125402, -0.46477553, -0.6828857 , -0.20149051,
       -0.34105813, -0.40245883, -0.48002104, -0.25923554, -0.33400519])